import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "./libs/utils";
import Navbar from "./components/Navbar";
import MadeBy from "./components/MadeBy";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Cipi Labs",
    template: "%s - Cipi Labs",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-background text-text decoration-text">
      <body className={cn(raleway.className, "relative overflow-hidden")}>
        <div className="flex h-svh w-full flex-col items-center justify-between overflow-auto pb-4 space-y-12">
          <Navbar />
          {children}
          <MadeBy />
        </div>

        <BackgroundAnimation />
      </body>
    </html>
  );
}

const BackgroundAnimation = () => (
  <>
    <div className="absolute left-[21%] top-1/4 -z-50 size-[400px] animate-blob rounded-full bg-primary-500 opacity-10 mix-blend-lighten blur-2xl" />
    <div className="animate-delay-2000 absolute bottom-[20%] right-[21%] -z-50 size-[400px] animate-blob rounded-full bg-[#7A4DB3] opacity-10 mix-blend-lighten blur-2xl" />
  </>
);
