import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Dev Playground",
    template: "%s - Dev Playground",
    absolute: "Products - Dev Playground",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-text bg-background decoration-text">
      <body className={raleway.className}>
        <Header />
        <div className="px-10 mx-auto pt-4 pb-7 max-w-[1300px]">{children}</div>
      </body>
    </html>
  );
}
